services:
  - type: web
    name: codewar-frontend
    env: static
    buildCommand: npm install && REACT_APP_API_URL=https://codewar-backend.onrender.com/api npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable 