branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - install-and-test
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      enforce_admins: true
      restrictions: null

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - install-and-test
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
      enforce_admins: false
      restrictions: null

  - name: staging
    protection:
      required_status_checks:
        strict: true
        contexts:
          - unit-tests
          - integration-tests
          - e2e-tests
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
      enforce_admins: false
      restrictions: null

  - name: 'release/*'
    protection:
      required_status_checks:
        strict: true
        contexts:
          - unit-tests
          - integration-tests
          - e2e-tests
          - security
          - quality-gate
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
      enforce_admins: true
      restrictions:
        users: []
        teams:
          - release-managers
        apps: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      lock_branch: false

  - name: 'contest/*'
    protection:
      required_status_checks:
        strict: true
        contexts:
          - unit-tests
          - integration-tests
          - contest-validation
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
      enforce_admins: false
      restrictions:
        users: []
        teams:
          - contest-managers
        apps: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      lock_branch: false

repository:
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: COMMIT_MESSAGES 