services:
  - type: web
    name: codewar-backend
    env: node
    buildCommand: |
      export NODE_VERSION=20.11.1
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install 20.11.1
      nvm use 20.11.1
      cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: codewar-frontend
          property: url

  - type: static
    name: codewar-frontend
    env: static
    buildCommand: |
      export NODE_VERSION=20.11.1
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install 20.11.1
      nvm use 20.11.1
      cd client && npm install && npm run build
    publishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: codewar-backend
          property: url
      - key: NODE_ENV
        value: production 