services:
  - type: web
    name: codewar-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: codewar-frontend
          property: url
      - key: NODE_VERSION
        value: 20.11.1

  - type: static
    name: codewar-frontend
    env: static
    buildCommand: cd client && npm install && NODE_OPTIONS=--openssl-legacy-provider npm run build
    publishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: codewar-backend
          property: url
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production 